# Funding options for this project
# GitHub will display a "Sponsor" button with these options

# Uncomment and add your GitHub username when you set up GitHub Sponsors
# github: YOUR_GITHUB_USERNAME

# Buy Me a Coffee
custom: ["https://buymeacoffee.com/smapps"]
